ClubRutaCFinal/Controllers/CalendariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClubRutaCFinal.Models;

namespace ClubRutaCFinal.Controllers
{
    public class CalendariosController : Controller
    {
        private ModeloClubContainer db = new ModeloClubContainer();

        // GET: Calendarios
        public ActionResult Index()
        {
            return View(db.CalendarioSet.ToList());
        }

        public ActionResult RegistrarCalendario()
        {
            return View(db.CalendarioSet.ToList());
        }

        // GET: Calendarios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Calendario calendario = db.CalendarioSet.Find(id);
            if (calendario == null)
            {
                return HttpNotFound();
            }
            return View(calendario);
        }

        // GET: Calendarios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Calendarios/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Fecha,Nombre,Distancia,Lugar,Estado")] Calendario calendario)
        {
            if (ModelState.IsValid)
            {
                db.CalendarioSet.Add(calendario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(calendario);
        }

        // GET: Calendarios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Calendario calendario = db.CalendarioSet.Find(id);
            if (calendario == null)
            {
                return HttpNotFound();
            }
            return View(calendario);
        }

        // POST: Calendarios/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Fecha,Nombre,Distancia,Lugar,Estado")] Calendario calendario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(calendario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(calendario);
        }

        // GET: Calendarios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Calendario calendario = db.CalendarioSet.Find(id);
            if (calendario == null)
            {
                return HttpNotFound();
            }
            return View(calendario);
        }

        // POST: Calendarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Calendario calendario = db.CalendarioSet.Find(id);
            db.CalendarioSet.Remove(calendario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClubRutaCFinal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubRutaCFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Podras Obtener Mayor Informacion en:";

            return View();
        }

        public ActionResult Multimedia()
        {
            ViewBag.Message = "Multimedia";

            return View();
        }

        public ActionResult Noticias()
        {
            ViewBag.Message = "Noticias";

            return View();
        }
    }
}

ClubRutaCFinal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClubRutaCFinal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Cantactenos";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Club Deportivo Ruta "C"<br />
    cra. 20 # 20 - 03<br />
    Barrio Acolsure <br />
    <abbr title="Phone">Telefono:</abbr>
    (310)803-1907
    (313)239-6457

     
</address>

<address>
    <strong>Correo:</strong>   <a href="mailto:franklin.2101@hotmail.com">franklin.2101@hotmail.com</a><br />
    <strong>Club:</strong> <a href="mailto:club-rutacC@gmail.com">club-rutacC@gmail.com</a>
</address>

ClubRutaCFinal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->

    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img class="uno-slide" src="~/imagenes/atleta.jpg" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1></h1>
                    <p></p>
                    <p>@Html.ActionLink("¡¡Iniciar sesión!!", "Login", "Account", routeValues: null, htmlAttributes: new { @class = "btn btn-lg btn-primary" })</p>
                </div>
            </div>
        </div>

        <div class="item">
            <img class="dos-slide" src="~/imagenes/mmb2016.jpg" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1></h1>

                    <p><a class="btn btn-lg btn-primary" href="http://www.mediamaratonbogota.com" role="button">¡¡Mas Información!!</a></p>
                </div>
            </div>
        </div>

        <div class="item">
            <img class="tres-slide" src="~/imagenes/rio2016.jpg" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1></h1>
                    <p></p>
                    <p><a class="btn btn-lg btn-primary" href="http://www.rio2016.com/es" role="button">¡¡Mas Información!!</a></p>
                </div>
            </div>
        </div>

        <div class="item">
            <img class="cuatro-slide" src="~/imagenes/atletismo.jpg" alt="Third slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Gran Prix Sur Colombiano de Atletismo</h1>
                    <p>
                        Fecha: 11 y 12 de Octubre del 2015
                        Inscribete ya
                        realizado en el estadio de Florencia-Caqueta
                    </p>
                    <p>@Html.ActionLink("¡¡INSCRIPCIÓN!!", "Index", "Inscripcions", null, htmlAttributes: new { @class = "btn btn-lg btn-primary" })

                </div>
            </div>
        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" src="~/imagenes/corredores.jpg" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div><!-- /.carousel -->

<div class="row">
    <div class="col-md-4">
        <img src="~/imagenes/calendario.gif" alt="Generic placeholder image" width="140" height="140">
        <h2>CALENDARIO</h2>
        <p>allí encontrará la información actualizada de todos los eventos locales, nacionales e internacionales.</p>
        <p>@Html.ActionLink("¡¡Detalles!!", "RegistrarCalendario", "Calendarios", null, htmlAttributes: new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <img src="~/imagenes/news.png" alt="Generic placeholder image" width="140" height="140">
        <h2>NOTICIAS</h2>
        <p>Las ultimas noticias del atletismo Regional y Nacional</p>
        <p>@Html.ActionLink("¡¡Detalles!!", "Noticias", "Home", null, htmlAttributes: new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <img src="~/imagenes/multimedia.png" alt="Generic placeholder image" width="140" height="140">
        <h2>MULTIMEDIA</h2>
        <p>En esta sección encontraras las imagenes y videos de los eventos Regionales y de nuestros atletas.</p>
        <p>@Html.ActionLink("¡¡Detalles!!", "Multimedia", "Home", null, htmlAttributes: new { @class = "btn btn-default" })</p>
    </div>
</div>

ClubRutaCFinal/Views/Home/Multimedia.cshtml
@{
    ViewBag.Title = "Multi";
}

<h1>Eventos Del Club</h1>

<p>Gran Prix Sur Colombiano de Atletismo 2014 <br /></p>
<div class="row">
    <div class="col-md-4">
        <img src="~/imagenes/granprix1.jpg" width="350" height="250">
    </div>

    <div class="col-md-4">
        <img src="~/imagenes/granprix2.jpg" width="350" height="250">

    </div>

    <div class="col-md-4">
        <img src="~/imagenes/granprix3.jpg" width="350" height="250">
    </div>
    <div><br /></div>
    <div class="col-md-4">
        <img src="~/imagenes/granprix4.jpg" width="350" height="250">
    </div>
    <div class="col-md-4">
        <img src="~/imagenes/granprix5.jpg" width="350" height="250">

    </div>
    <div class="col-md-4">
        <img src="~/imagenes/granprix6.jpg" width="350" height="250">
    </div>
    <br />


</div>

ClubRutaCFinal/Views/Home/Noticias.cshtml
@{
    ViewBag.Title = "";
}

<!-- START THE FEATURETTES -->
<h1>Noticias</h1>
<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">  Caterine Ibargüen completó el objetivo nacional en Toronto: 25 oros</h2>
        <p class="lead">La antioqueña Caterine Ibargüen cumplió este martes con los pronósticos de medalla de oro en el salto triple del atletismo de los XVII Juegos Panamericanos Toronto 2015 y llevó a la delegación nacional a cumplir el gran objetivo de las justas: superar los 24 oros logrados en Guadalajara-2011, y son 25 en Canadá.

</p>
   
      

        
     </div>
    <div class="col-md-5">
        <img class="featurette-image img-responsive center-block" src="~/imagenes/cate.png" alt="Generic placeholder image">
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7 col-md-push-5">
        <h2 class="featurette-heading">ANTIOQUEÑOS Y COLOMBIANOS A JUEGOS PANAMERICANOS TORONTO 2015</h2>
       
         <p class="lead">Esta es la lista final para Toronto 2015,  la Liga de Atletismo felicita a los atletas seleccionados. </p>
    </div>
    <div class="col-md-5 col-md-pull-7">
        <img class="featurette-image img-responsive center-block" src="~/imagenes/T.png" alt="Generic placeholder image">
    </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
    <div class="col-md-7">
        <h2 class="featurette-heading">Rafith se metió a los Olímpicos y Muriel Coneo hizo récord nacional en el Prix de Ponce</h2>
        <p class="lead">El antioqueño Rafith Rodríguez hizo la marca mínima para los Juegos Olímpicos de Rio 2016 y Muriel Coneo, tuvo una actuación histórica en el Grand Prix de Ponce, uno de los más importantes de América y que se llevó a cabo el pasado 23 de Mayo.
</p>
    </div>
    <div class="col-md-5">
        <img class="featurette-image img-responsive center-block" src="~/imagenes/rafi.png" alt="Generic placeholder image">
    </div>
</div>

<hr class="featurette-divider">

<!-- /END THE FEATURETTES -->