ClubRutaCFinal/Controllers/HistoriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClubRutaCFinal.Models;

namespace ClubRutaCFinal.Controllers
{
    public class HistoriasController : Controller
    {
        private ModeloClubContainer db = new ModeloClubContainer();

        // GET: Historias
        public ActionResult Index()
        {
            return View(db.HistoriaSet.ToList());
        }

        public ActionResult HistoriaDetalle()
        {
            return View(db.HistoriaSet.ToList());
        }

        // GET: Historias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Historia historia = db.HistoriaSet.Find(id);
            if (historia == null)
            {
                return HttpNotFound();
            }
            return View(historia);
        }

        // GET: Historias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Historias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nombre,Apellido,Fecha_nacimiento,Prueba,Marca,Detalle")] Historia historia)
        {
            if (ModelState.IsValid)
            {
                db.HistoriaSet.Add(historia);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(historia);
        }

        // GET: Historias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Historia historia = db.HistoriaSet.Find(id);
            if (historia == null)
            {
                return HttpNotFound();
            }
            return View(historia);
        }

        // POST: Historias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Apellido,Fecha_nacimiento,Prueba,Marca,Detalle")] Historia historia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(historia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(historia);
        }

        // GET: Historias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Historia historia = db.HistoriaSet.Find(id);
            if (historia == null)
            {
                return HttpNotFound();
            }
            return View(historia);
        }

        // POST: Historias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Historia historia = db.HistoriaSet.Find(id);
            db.HistoriaSet.Remove(historia);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClubRutaCFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width = dispositivo de ancho, escala inicial = 1, de máxima escala = 1, el usuario escalable = no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link href='http://fonts.googleapis.com/css?family=Anton' rel='stylesheet' type='text/css'>

    <title>@ViewBag.Title Club_deportivo_Ruta_C</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/" rel="stylesheet" />
    <link rel="icon" href="~/imagenes/atleta1.jpg">

</head>
<body>

    <img id="bge" src="~/imagenes/fondo2.jpg" class="img-responsive" alt="background"  />

    <div id="dvWrapInset">
        <h1 class="titulo">CLUB DEPORTIVO RUTA "C"</h1>
    </div>




    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-inverse navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                       @* <ul class="nav navbar-nav">
        <li class="active">@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">NOSOTROS <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li>@Html.ActionLink("Mision", "Index", "Contenidoes")</li>
                <li>@Html.ActionLink("Vision", "Mision", "Contenidoes")</li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Club</li>
                <li>@Html.ActionLink("Historia", "HistoriaDetalle", "Historias")</li>
                <li> @Html.ActionLink("Socios", "DetalleSocio", "Socios")</li>
            </ul>
        </li>
        <li>@Html.ActionLink("Atletas", "Atletas_detalles", "Ficha_Atleta")</li>
        <li>@Html.ActionLink("Marcas", "DetalleMarcas", "Marcas")</li>
        <li>@Html.ActionLink("Calendario", "RegistrarCalendario", "Calendarios")</li>
        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
    </ul>*@
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </nav>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-4">
                    Club Deportivo Ruta "C"<br />
                    <p>
                        <br />
                        Estadio Alberto Guitrago Hoyos <br />
                        Carrera 11 #8-3br   <br />
                        Cel: 313-2396457br      <br />
                        Email: club-rutacC@gmail.com
                    </p>

                </div>
                <div class="col-md-4">

                    <p>Paginas de Interes <br /></p><br />
                    <p><a class="" href="http://colombiacorre.com.co/" role="link">- COLOMBIA CORRE</a></p>
                    <p><a class="" href=" http://icdtcaqueta.gov.co/" role="link">- ICDT CAQUETA</a></p>
                    <p><a class="" href="http://www.coc.org.co/" role="link">- COMITE OLIMPICO COLOMBIANO</a></p>
                    <p><a class="" href="http://runningcolombia.com/app/" role="link">- RUNNING COLOMBIA</a></p>

                </div>
                <div class="col-md-4">
                    <div><img src="~/imagenes/liatleca.jpg" width="250" height="150" /> </div>
                    <p><a class="" href="https://www.facebook.com/pages/Liga-De-Atletismo-del-Caquet%C3%A1/843411355697045?fref=ts" role="link">LIGA DE ATLETISMO DEL CAQUETA</a></p>

                </div>
            </div>
            <hr />
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>